services:
  redis-stack:
    image: redis/redis-stack:7.4.0-v8
    container_name: redis-stack
    networks:
      - llm-gateway-network
    ports:
      - "6379:6379"
      - "8081:8001"
    environment:
      - REDIS_ARGS=--requirepass ${REDIS_PASSWORD}
    volumes:
      - redis-data:/data

  api:
    build: .
    container_name: llm-gateway-api
    networks:
      - llm-gateway-network
    ports:
      - "8000:80"
    environment:
      - REDIS_HOST=redis-stack
      - REDIS_PORT=6379
      - LLM_API_KEY=${LLM_API_KEY}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - HF_HOME=/app/model_cache
      - LLM_MODEL=groq/llama-3.1-8b-instant
    depends_on:
      - redis-stack

volumes:
  redis-data:
    driver: local

networks:
  llm-gateway-network:
    driver: bridge